/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniversidadRouteImport } from './routes/universidad'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as PruebaDeNivelRouteImport } from './routes/prueba-de-nivel'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as CondicionesRouteImport } from './routes/condiciones'
import { Route as AprendizajeRouteImport } from './routes/aprendizaje'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UniversidadNoticiasRouteImport } from './routes/universidad.noticias'
import { Route as UniversidadHorarioRouteImport } from './routes/universidad.horario'
import { Route as UniversidadExamenesRouteImport } from './routes/universidad.examenes'
import { Route as UniversidadAprendizajeRouteImport } from './routes/universidad.aprendizaje'
import { Route as PanelTareasNuevaRouteImport } from './routes/panel_.tareas.nueva'
import { Route as PanelTareasHomeworkIdRouteImport } from './routes/panel_.tareas.$homeworkId'
import { Route as PanelAlumnosStudentIdRouteImport } from './routes/panel_.alumnos.$studentId'
import { Route as AprendizajeTareaHomeworkIdRouteImport } from './routes/aprendizaje_.tarea.$homeworkId'
import { Route as AprendizajeRedaccionHomeworkIdRouteImport } from './routes/aprendizaje_.redaccion.$homeworkId'
import { Route as AprendizajeLecturaHomeworkIdRouteImport } from './routes/aprendizaje_.lectura.$homeworkId'
import { Route as AprendizajeEscuchaHomeworkIdRouteImport } from './routes/aprendizaje_.escucha.$homeworkId'
import { Route as UniversidadAprendizajeTareaHomeworkIdRouteImport } from './routes/universidad.aprendizaje.tarea.$homeworkId'

const UniversidadRoute = UniversidadRouteImport.update({
  id: '/universidad',
  path: '/universidad',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const PruebaDeNivelRoute = PruebaDeNivelRouteImport.update({
  id: '/prueba-de-nivel',
  path: '/prueba-de-nivel',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicionesRoute = CondicionesRouteImport.update({
  id: '/condiciones',
  path: '/condiciones',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizajeRoute = AprendizajeRouteImport.update({
  id: '/aprendizaje',
  path: '/aprendizaje',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversidadNoticiasRoute = UniversidadNoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => UniversidadRoute,
} as any)
const UniversidadHorarioRoute = UniversidadHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => UniversidadRoute,
} as any)
const UniversidadExamenesRoute = UniversidadExamenesRouteImport.update({
  id: '/examenes',
  path: '/examenes',
  getParentRoute: () => UniversidadRoute,
} as any)
const UniversidadAprendizajeRoute = UniversidadAprendizajeRouteImport.update({
  id: '/aprendizaje',
  path: '/aprendizaje',
  getParentRoute: () => UniversidadRoute,
} as any)
const PanelTareasNuevaRoute = PanelTareasNuevaRouteImport.update({
  id: '/panel_/tareas/nueva',
  path: '/panel/tareas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTareasHomeworkIdRoute = PanelTareasHomeworkIdRouteImport.update({
  id: '/panel_/tareas/$homeworkId',
  path: '/panel/tareas/$homeworkId',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAlumnosStudentIdRoute = PanelAlumnosStudentIdRouteImport.update({
  id: '/panel_/alumnos/$studentId',
  path: '/panel/alumnos/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizajeTareaHomeworkIdRoute =
  AprendizajeTareaHomeworkIdRouteImport.update({
    id: '/aprendizaje_/tarea/$homeworkId',
    path: '/aprendizaje/tarea/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AprendizajeRedaccionHomeworkIdRoute =
  AprendizajeRedaccionHomeworkIdRouteImport.update({
    id: '/aprendizaje_/redaccion/$homeworkId',
    path: '/aprendizaje/redaccion/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AprendizajeLecturaHomeworkIdRoute =
  AprendizajeLecturaHomeworkIdRouteImport.update({
    id: '/aprendizaje_/lectura/$homeworkId',
    path: '/aprendizaje/lectura/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AprendizajeEscuchaHomeworkIdRoute =
  AprendizajeEscuchaHomeworkIdRouteImport.update({
    id: '/aprendizaje_/escucha/$homeworkId',
    path: '/aprendizaje/escucha/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const UniversidadAprendizajeTareaHomeworkIdRoute =
  UniversidadAprendizajeTareaHomeworkIdRouteImport.update({
    id: '/tarea/$homeworkId',
    path: '/tarea/$homeworkId',
    getParentRoute: () => UniversidadAprendizajeRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/condiciones': typeof CondicionesRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/prueba-de-nivel': typeof PruebaDeNivelRoute
  '/reservas': typeof ReservasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/universidad': typeof UniversidadRouteWithChildren
  '/universidad/aprendizaje': typeof UniversidadAprendizajeRouteWithChildren
  '/universidad/examenes': typeof UniversidadExamenesRoute
  '/universidad/horario': typeof UniversidadHorarioRoute
  '/universidad/noticias': typeof UniversidadNoticiasRoute
  '/aprendizaje/escucha/$homeworkId': typeof AprendizajeEscuchaHomeworkIdRoute
  '/aprendizaje/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel/tareas/nueva': typeof PanelTareasNuevaRoute
  '/universidad/aprendizaje/tarea/$homeworkId': typeof UniversidadAprendizajeTareaHomeworkIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/condiciones': typeof CondicionesRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/prueba-de-nivel': typeof PruebaDeNivelRoute
  '/reservas': typeof ReservasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/universidad': typeof UniversidadRouteWithChildren
  '/universidad/aprendizaje': typeof UniversidadAprendizajeRouteWithChildren
  '/universidad/examenes': typeof UniversidadExamenesRoute
  '/universidad/horario': typeof UniversidadHorarioRoute
  '/universidad/noticias': typeof UniversidadNoticiasRoute
  '/aprendizaje/escucha/$homeworkId': typeof AprendizajeEscuchaHomeworkIdRoute
  '/aprendizaje/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel/tareas/nueva': typeof PanelTareasNuevaRoute
  '/universidad/aprendizaje/tarea/$homeworkId': typeof UniversidadAprendizajeTareaHomeworkIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/condiciones': typeof CondicionesRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/prueba-de-nivel': typeof PruebaDeNivelRoute
  '/reservas': typeof ReservasRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/universidad': typeof UniversidadRouteWithChildren
  '/universidad/aprendizaje': typeof UniversidadAprendizajeRouteWithChildren
  '/universidad/examenes': typeof UniversidadExamenesRoute
  '/universidad/horario': typeof UniversidadHorarioRoute
  '/universidad/noticias': typeof UniversidadNoticiasRoute
  '/aprendizaje_/escucha/$homeworkId': typeof AprendizajeEscuchaHomeworkIdRoute
  '/aprendizaje_/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje_/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje_/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel_/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel_/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel_/tareas/nueva': typeof PanelTareasNuevaRoute
  '/universidad/aprendizaje/tarea/$homeworkId': typeof UniversidadAprendizajeTareaHomeworkIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprendizaje'
    | '/condiciones'
    | '/cuenta'
    | '/panel'
    | '/prueba-de-nivel'
    | '/reservas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/universidad'
    | '/universidad/aprendizaje'
    | '/universidad/examenes'
    | '/universidad/horario'
    | '/universidad/noticias'
    | '/aprendizaje/escucha/$homeworkId'
    | '/aprendizaje/lectura/$homeworkId'
    | '/aprendizaje/redaccion/$homeworkId'
    | '/aprendizaje/tarea/$homeworkId'
    | '/panel/alumnos/$studentId'
    | '/panel/tareas/$homeworkId'
    | '/panel/tareas/nueva'
    | '/universidad/aprendizaje/tarea/$homeworkId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprendizaje'
    | '/condiciones'
    | '/cuenta'
    | '/panel'
    | '/prueba-de-nivel'
    | '/reservas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/universidad'
    | '/universidad/aprendizaje'
    | '/universidad/examenes'
    | '/universidad/horario'
    | '/universidad/noticias'
    | '/aprendizaje/escucha/$homeworkId'
    | '/aprendizaje/lectura/$homeworkId'
    | '/aprendizaje/redaccion/$homeworkId'
    | '/aprendizaje/tarea/$homeworkId'
    | '/panel/alumnos/$studentId'
    | '/panel/tareas/$homeworkId'
    | '/panel/tareas/nueva'
    | '/universidad/aprendizaje/tarea/$homeworkId'
  id:
    | '__root__'
    | '/'
    | '/aprendizaje'
    | '/condiciones'
    | '/cuenta'
    | '/panel'
    | '/prueba-de-nivel'
    | '/reservas'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/universidad'
    | '/universidad/aprendizaje'
    | '/universidad/examenes'
    | '/universidad/horario'
    | '/universidad/noticias'
    | '/aprendizaje_/escucha/$homeworkId'
    | '/aprendizaje_/lectura/$homeworkId'
    | '/aprendizaje_/redaccion/$homeworkId'
    | '/aprendizaje_/tarea/$homeworkId'
    | '/panel_/alumnos/$studentId'
    | '/panel_/tareas/$homeworkId'
    | '/panel_/tareas/nueva'
    | '/universidad/aprendizaje/tarea/$homeworkId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendizajeRoute: typeof AprendizajeRoute
  CondicionesRoute: typeof CondicionesRoute
  CuentaRoute: typeof CuentaRoute
  PanelRoute: typeof PanelRoute
  PruebaDeNivelRoute: typeof PruebaDeNivelRoute
  ReservasRoute: typeof ReservasRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  UniversidadRoute: typeof UniversidadRouteWithChildren
  AprendizajeEscuchaHomeworkIdRoute: typeof AprendizajeEscuchaHomeworkIdRoute
  AprendizajeLecturaHomeworkIdRoute: typeof AprendizajeLecturaHomeworkIdRoute
  AprendizajeRedaccionHomeworkIdRoute: typeof AprendizajeRedaccionHomeworkIdRoute
  AprendizajeTareaHomeworkIdRoute: typeof AprendizajeTareaHomeworkIdRoute
  PanelAlumnosStudentIdRoute: typeof PanelAlumnosStudentIdRoute
  PanelTareasHomeworkIdRoute: typeof PanelTareasHomeworkIdRoute
  PanelTareasNuevaRoute: typeof PanelTareasNuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/universidad': {
      id: '/universidad'
      path: '/universidad'
      fullPath: '/universidad'
      preLoaderRoute: typeof UniversidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prueba-de-nivel': {
      id: '/prueba-de-nivel'
      path: '/prueba-de-nivel'
      fullPath: '/prueba-de-nivel'
      preLoaderRoute: typeof PruebaDeNivelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condiciones': {
      id: '/condiciones'
      path: '/condiciones'
      fullPath: '/condiciones'
      preLoaderRoute: typeof CondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje': {
      id: '/aprendizaje'
      path: '/aprendizaje'
      fullPath: '/aprendizaje'
      preLoaderRoute: typeof AprendizajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidad/noticias': {
      id: '/universidad/noticias'
      path: '/noticias'
      fullPath: '/universidad/noticias'
      preLoaderRoute: typeof UniversidadNoticiasRouteImport
      parentRoute: typeof UniversidadRoute
    }
    '/universidad/horario': {
      id: '/universidad/horario'
      path: '/horario'
      fullPath: '/universidad/horario'
      preLoaderRoute: typeof UniversidadHorarioRouteImport
      parentRoute: typeof UniversidadRoute
    }
    '/universidad/examenes': {
      id: '/universidad/examenes'
      path: '/examenes'
      fullPath: '/universidad/examenes'
      preLoaderRoute: typeof UniversidadExamenesRouteImport
      parentRoute: typeof UniversidadRoute
    }
    '/universidad/aprendizaje': {
      id: '/universidad/aprendizaje'
      path: '/aprendizaje'
      fullPath: '/universidad/aprendizaje'
      preLoaderRoute: typeof UniversidadAprendizajeRouteImport
      parentRoute: typeof UniversidadRoute
    }
    '/panel_/tareas/nueva': {
      id: '/panel_/tareas/nueva'
      path: '/panel/tareas/nueva'
      fullPath: '/panel/tareas/nueva'
      preLoaderRoute: typeof PanelTareasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/tareas/$homeworkId': {
      id: '/panel_/tareas/$homeworkId'
      path: '/panel/tareas/$homeworkId'
      fullPath: '/panel/tareas/$homeworkId'
      preLoaderRoute: typeof PanelTareasHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/alumnos/$studentId': {
      id: '/panel_/alumnos/$studentId'
      path: '/panel/alumnos/$studentId'
      fullPath: '/panel/alumnos/$studentId'
      preLoaderRoute: typeof PanelAlumnosStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/tarea/$homeworkId': {
      id: '/aprendizaje_/tarea/$homeworkId'
      path: '/aprendizaje/tarea/$homeworkId'
      fullPath: '/aprendizaje/tarea/$homeworkId'
      preLoaderRoute: typeof AprendizajeTareaHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/redaccion/$homeworkId': {
      id: '/aprendizaje_/redaccion/$homeworkId'
      path: '/aprendizaje/redaccion/$homeworkId'
      fullPath: '/aprendizaje/redaccion/$homeworkId'
      preLoaderRoute: typeof AprendizajeRedaccionHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/lectura/$homeworkId': {
      id: '/aprendizaje_/lectura/$homeworkId'
      path: '/aprendizaje/lectura/$homeworkId'
      fullPath: '/aprendizaje/lectura/$homeworkId'
      preLoaderRoute: typeof AprendizajeLecturaHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/escucha/$homeworkId': {
      id: '/aprendizaje_/escucha/$homeworkId'
      path: '/aprendizaje/escucha/$homeworkId'
      fullPath: '/aprendizaje/escucha/$homeworkId'
      preLoaderRoute: typeof AprendizajeEscuchaHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universidad/aprendizaje/tarea/$homeworkId': {
      id: '/universidad/aprendizaje/tarea/$homeworkId'
      path: '/tarea/$homeworkId'
      fullPath: '/universidad/aprendizaje/tarea/$homeworkId'
      preLoaderRoute: typeof UniversidadAprendizajeTareaHomeworkIdRouteImport
      parentRoute: typeof UniversidadAprendizajeRoute
    }
  }
}

interface UniversidadAprendizajeRouteChildren {
  UniversidadAprendizajeTareaHomeworkIdRoute: typeof UniversidadAprendizajeTareaHomeworkIdRoute
}

const UniversidadAprendizajeRouteChildren: UniversidadAprendizajeRouteChildren =
  {
    UniversidadAprendizajeTareaHomeworkIdRoute:
      UniversidadAprendizajeTareaHomeworkIdRoute,
  }

const UniversidadAprendizajeRouteWithChildren =
  UniversidadAprendizajeRoute._addFileChildren(
    UniversidadAprendizajeRouteChildren,
  )

interface UniversidadRouteChildren {
  UniversidadAprendizajeRoute: typeof UniversidadAprendizajeRouteWithChildren
  UniversidadExamenesRoute: typeof UniversidadExamenesRoute
  UniversidadHorarioRoute: typeof UniversidadHorarioRoute
  UniversidadNoticiasRoute: typeof UniversidadNoticiasRoute
}

const UniversidadRouteChildren: UniversidadRouteChildren = {
  UniversidadAprendizajeRoute: UniversidadAprendizajeRouteWithChildren,
  UniversidadExamenesRoute: UniversidadExamenesRoute,
  UniversidadHorarioRoute: UniversidadHorarioRoute,
  UniversidadNoticiasRoute: UniversidadNoticiasRoute,
}

const UniversidadRouteWithChildren = UniversidadRoute._addFileChildren(
  UniversidadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendizajeRoute: AprendizajeRoute,
  CondicionesRoute: CondicionesRoute,
  CuentaRoute: CuentaRoute,
  PanelRoute: PanelRoute,
  PruebaDeNivelRoute: PruebaDeNivelRoute,
  ReservasRoute: ReservasRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  UniversidadRoute: UniversidadRouteWithChildren,
  AprendizajeEscuchaHomeworkIdRoute: AprendizajeEscuchaHomeworkIdRoute,
  AprendizajeLecturaHomeworkIdRoute: AprendizajeLecturaHomeworkIdRoute,
  AprendizajeRedaccionHomeworkIdRoute: AprendizajeRedaccionHomeworkIdRoute,
  AprendizajeTareaHomeworkIdRoute: AprendizajeTareaHomeworkIdRoute,
  PanelAlumnosStudentIdRoute: PanelAlumnosStudentIdRoute,
  PanelTareasHomeworkIdRoute: PanelTareasHomeworkIdRoute,
  PanelTareasNuevaRoute: PanelTareasNuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
