/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as RecursosRouteImport } from './routes/recursos'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as AprendizajeRouteImport } from './routes/aprendizaje'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PanelTareasNuevaRouteImport } from './routes/panel_.tareas.nueva'
import { Route as PanelTareasHomeworkIdRouteImport } from './routes/panel_.tareas.$homeworkId'
import { Route as PanelAlumnosStudentIdRouteImport } from './routes/panel_.alumnos.$studentId'
import { Route as AprendizajeTareaHomeworkIdRouteImport } from './routes/aprendizaje_.tarea.$homeworkId'
import { Route as AprendizajeRedaccionHomeworkIdRouteImport } from './routes/aprendizaje_.redaccion.$homeworkId'
import { Route as AprendizajeLecturaHomeworkIdRouteImport } from './routes/aprendizaje_.lectura.$homeworkId'

const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const RecursosRoute = RecursosRouteImport.update({
  id: '/recursos',
  path: '/recursos',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizajeRoute = AprendizajeRouteImport.update({
  id: '/aprendizaje',
  path: '/aprendizaje',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTareasNuevaRoute = PanelTareasNuevaRouteImport.update({
  id: '/panel_/tareas/nueva',
  path: '/panel/tareas/nueva',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelTareasHomeworkIdRoute = PanelTareasHomeworkIdRouteImport.update({
  id: '/panel_/tareas/$homeworkId',
  path: '/panel/tareas/$homeworkId',
  getParentRoute: () => rootRouteImport,
} as any)
const PanelAlumnosStudentIdRoute = PanelAlumnosStudentIdRouteImport.update({
  id: '/panel_/alumnos/$studentId',
  path: '/panel/alumnos/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AprendizajeTareaHomeworkIdRoute =
  AprendizajeTareaHomeworkIdRouteImport.update({
    id: '/aprendizaje_/tarea/$homeworkId',
    path: '/aprendizaje/tarea/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AprendizajeRedaccionHomeworkIdRoute =
  AprendizajeRedaccionHomeworkIdRouteImport.update({
    id: '/aprendizaje_/redaccion/$homeworkId',
    path: '/aprendizaje/redaccion/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AprendizajeLecturaHomeworkIdRoute =
  AprendizajeLecturaHomeworkIdRouteImport.update({
    id: '/aprendizaje_/lectura/$homeworkId',
    path: '/aprendizaje/lectura/$homeworkId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/recursos': typeof RecursosRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/aprendizaje/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel/tareas/nueva': typeof PanelTareasNuevaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/recursos': typeof RecursosRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/aprendizaje/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel/tareas/nueva': typeof PanelTareasNuevaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aprendizaje': typeof AprendizajeRoute
  '/cuenta': typeof CuentaRoute
  '/panel': typeof PanelRoute
  '/recursos': typeof RecursosRoute
  '/reservas': typeof ReservasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/aprendizaje_/lectura/$homeworkId': typeof AprendizajeLecturaHomeworkIdRoute
  '/aprendizaje_/redaccion/$homeworkId': typeof AprendizajeRedaccionHomeworkIdRoute
  '/aprendizaje_/tarea/$homeworkId': typeof AprendizajeTareaHomeworkIdRoute
  '/panel_/alumnos/$studentId': typeof PanelAlumnosStudentIdRoute
  '/panel_/tareas/$homeworkId': typeof PanelTareasHomeworkIdRoute
  '/panel_/tareas/nueva': typeof PanelTareasNuevaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aprendizaje'
    | '/cuenta'
    | '/panel'
    | '/recursos'
    | '/reservas'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/aprendizaje/lectura/$homeworkId'
    | '/aprendizaje/redaccion/$homeworkId'
    | '/aprendizaje/tarea/$homeworkId'
    | '/panel/alumnos/$studentId'
    | '/panel/tareas/$homeworkId'
    | '/panel/tareas/nueva'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aprendizaje'
    | '/cuenta'
    | '/panel'
    | '/recursos'
    | '/reservas'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/aprendizaje/lectura/$homeworkId'
    | '/aprendizaje/redaccion/$homeworkId'
    | '/aprendizaje/tarea/$homeworkId'
    | '/panel/alumnos/$studentId'
    | '/panel/tareas/$homeworkId'
    | '/panel/tareas/nueva'
  id:
    | '__root__'
    | '/'
    | '/aprendizaje'
    | '/cuenta'
    | '/panel'
    | '/recursos'
    | '/reservas'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/aprendizaje_/lectura/$homeworkId'
    | '/aprendizaje_/redaccion/$homeworkId'
    | '/aprendizaje_/tarea/$homeworkId'
    | '/panel_/alumnos/$studentId'
    | '/panel_/tareas/$homeworkId'
    | '/panel_/tareas/nueva'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AprendizajeRoute: typeof AprendizajeRoute
  CuentaRoute: typeof CuentaRoute
  PanelRoute: typeof PanelRoute
  RecursosRoute: typeof RecursosRoute
  ReservasRoute: typeof ReservasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  AprendizajeLecturaHomeworkIdRoute: typeof AprendizajeLecturaHomeworkIdRoute
  AprendizajeRedaccionHomeworkIdRoute: typeof AprendizajeRedaccionHomeworkIdRoute
  AprendizajeTareaHomeworkIdRoute: typeof AprendizajeTareaHomeworkIdRoute
  PanelAlumnosStudentIdRoute: typeof PanelAlumnosStudentIdRoute
  PanelTareasHomeworkIdRoute: typeof PanelTareasHomeworkIdRoute
  PanelTareasNuevaRoute: typeof PanelTareasNuevaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recursos': {
      id: '/recursos'
      path: '/recursos'
      fullPath: '/recursos'
      preLoaderRoute: typeof RecursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje': {
      id: '/aprendizaje'
      path: '/aprendizaje'
      fullPath: '/aprendizaje'
      preLoaderRoute: typeof AprendizajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/tareas/nueva': {
      id: '/panel_/tareas/nueva'
      path: '/panel/tareas/nueva'
      fullPath: '/panel/tareas/nueva'
      preLoaderRoute: typeof PanelTareasNuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/tareas/$homeworkId': {
      id: '/panel_/tareas/$homeworkId'
      path: '/panel/tareas/$homeworkId'
      fullPath: '/panel/tareas/$homeworkId'
      preLoaderRoute: typeof PanelTareasHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panel_/alumnos/$studentId': {
      id: '/panel_/alumnos/$studentId'
      path: '/panel/alumnos/$studentId'
      fullPath: '/panel/alumnos/$studentId'
      preLoaderRoute: typeof PanelAlumnosStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/tarea/$homeworkId': {
      id: '/aprendizaje_/tarea/$homeworkId'
      path: '/aprendizaje/tarea/$homeworkId'
      fullPath: '/aprendizaje/tarea/$homeworkId'
      preLoaderRoute: typeof AprendizajeTareaHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/redaccion/$homeworkId': {
      id: '/aprendizaje_/redaccion/$homeworkId'
      path: '/aprendizaje/redaccion/$homeworkId'
      fullPath: '/aprendizaje/redaccion/$homeworkId'
      preLoaderRoute: typeof AprendizajeRedaccionHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aprendizaje_/lectura/$homeworkId': {
      id: '/aprendizaje_/lectura/$homeworkId'
      path: '/aprendizaje/lectura/$homeworkId'
      fullPath: '/aprendizaje/lectura/$homeworkId'
      preLoaderRoute: typeof AprendizajeLecturaHomeworkIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AprendizajeRoute: AprendizajeRoute,
  CuentaRoute: CuentaRoute,
  PanelRoute: PanelRoute,
  RecursosRoute: RecursosRoute,
  ReservasRoute: ReservasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  AprendizajeLecturaHomeworkIdRoute: AprendizajeLecturaHomeworkIdRoute,
  AprendizajeRedaccionHomeworkIdRoute: AprendizajeRedaccionHomeworkIdRoute,
  AprendizajeTareaHomeworkIdRoute: AprendizajeTareaHomeworkIdRoute,
  PanelAlumnosStudentIdRoute: PanelAlumnosStudentIdRoute,
  PanelTareasHomeworkIdRoute: PanelTareasHomeworkIdRoute,
  PanelTareasNuevaRoute: PanelTareasNuevaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
